Repository IceKhan13/purplecaffeine, pull requests merged in 2023-07, with the labels that each got.

#77 [DOC] Add qiskit sphinx theme
  docs/_static/custom.css
  docs/conf.py
  docs/guides/04_setup_api.ipynb
  docs/guides/04_setup_api.md
  docs/guides/index.rst
  docs/images/transparent_logo.png
  docs/index.rst
  docs/requirements-doc.txt
Labels: documentation

#78 Docs: readme update
  README.md
Labels: documentation

#81 Add version tracking
  .gitignore
  api_server/core/migrations/0003_trial_versions.py
  api_server/core/models.py
  client/purplecaffeine/core.py
  client/tests/test_trial.py
Labels: enhancement

#79 Add Ecosystem badge
  README.md
Labels: documentation

#75 Add CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, enhancement
